#!/usr/bin/env bash
set -eEuo pipefail

terraform state pull >/dev/null

TARGETS=""
for RESOURCE in $(terraform state list | grep 'google_service_account_key'); do
  TARGETS="${TARGETS} -replace=${RESOURCE}"
done

terraform apply ${TARGETS}
