#!/usr/bin/env bash
set -eEuo pipefail

terraform state pull >/dev/null

for RESOURCE in $(terraform state list | grep 'google_service_account_key'); do
  terraform taint "${RESOURCE}"
done

terraform apply
