name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: 'read'
  statuses: 'write'

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd' # ratchet:hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: '1.11'

      - run: |-
          terraform fmt -check -diff

      - run: |-
          terraform init -backend=false -input=false

      - run: |-
          terraform validate
